Models/ErrorViewModel.cs
namespace Practica4.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Practica4.Models;

namespace Practica4.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/SentirController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.ML;

namespace Practica4.Controllers
{

    public class SentirController : Controller
    {
        private readonly ILogger<SentirController> _logger;
        private readonly PredictionEnginePool<Sentir.ModelInput, Sentir.ModelOutput> _predictionEnginePool;

        public SentirController(ILogger<SentirController> logger, PredictionEnginePool<Sentir.ModelInput, Sentir.ModelOutput> predictionEnginePool)
        {
            _logger = logger;
            _predictionEnginePool = predictionEnginePool;
        }

        public IActionResult Index()
        
        {
            return View("Views/Sentir/Index.cshtml");
        }

        [HttpPost]
        public IActionResult Comentario(string comentario)
        {
            var input = new Sentir.ModelInput
            {
                Col0 = comentario
            };


           Sentir.ModelOutput prediction = _predictionEnginePool.Predict(input);


            ViewBag.Resultado = prediction.PredictedLabel;

             return View("Views/Sentir/Evaluacion.cshtml");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Sentir/Evaluacion.cshtml
@{
    ViewData["Title"] = "Evaluación";
}
<br><br><br><br><br><br><br><br><br><br><br><br>
<h2 style="text-align: center;">@ViewData["Title"]</h2>

<div style="text-align: center;" id="evaluacion">
        Resultado: @ViewBag.Resultado
</div>

<style>
    body{
    background-color: #8DC29B;
    }

    h2{
        color: #CED396;
    }

    .id{
        color: red;
    }
</style>

Views/Sentir/Index.cshtml
@{
    ViewData["Title"] = "Comentarios";
}

<h2>@ViewData["Title"]</h2>

<form  asp-action="Comentario" method="post">
    <div  class="form-group">
        <label  style="color:white"for="comentario">Comentario en ingles:</label>
        <textarea  class="form-control" id="comentario" name="comentario" rows="5" required></textarea>
    </div>
    <br>
    <button style="background: rgb(192, 163, 110); border: red; type="submit" class="btn btn-primary">Comentar</button>
</form>

<div id="resultado" style="display:none;"></div>

<style>
    body{
  
   width: 100%;
   background-color: #000;
   background-image: url(https://i.pinimg.com/originals/b0/7b/5b/b07b5bbfc32b4958810d59a79cd3aac9.gif);
   background-position: center;
   background-repeat: no-repeat;
   background-size: 25%;
   
}
    h2{
        color: rgb(238, 238, 181);
        text-align: center;
    }

    label{

    }

    button{
       width: 120px; 
  margin-left: 50%;
  transform: translateX(-50%);
    }


</style>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practica4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sentir" asp-action="Index">Comentario</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div  style="height"class="container">
            &copy; 2023 - Practica4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>